[package]
name = "plx-model"
description = "FE-Modell: Materialien, Sections, Steps, Randbedingungen, Lasten, Commands"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
plx-core.workspace = true
plx-mesh.workspace = true

[lints]
workspace = true
